#!/bin/bash

socketIsOpen=2

# Test remote host:port availability (TCP-only as UDP does not reply)
function checkRemotePort() {
    (echo >/dev/tcp/$OPENSHIFT_${openshift.jdbc.module.name}_DB_HOST/$OPENSHIFT_${openshift.jdbc.module.name}_DB_PORT) &>/dev/null
    if [ $? -eq 0 ]; then
        echo -en "\nbuild.checkRemotePort() : $OPENSHIFT_${openshift.jdbc.module.name}_DB_HOST:$OPENSHIFT_${openshift.jdbc.module.name}_DB_PORT is open.\n\n"
    else
        echo -en "\nbuild.checkRemotePort() : $OPENSHIFT_${openshift.jdbc.module.name}_DB_HOST:$OPENSHIFT_${openshift.jdbc.module.name}_DB_PORT is closed. ... will now exit\n\n"
        exit 1
    fi
}

# checkRemotePort
