#!/bin/bash

echo "** inside deploy"

printJvmCount() {
    mkdir -p ${OPENSHIFT_DATA_DIR}/log
    echo `date` > ${OPENSHIFT_DATA_DIR}/log/deploy.log
    for jProc in `ps -C java -o pid=`;
    do
        echo "java process id = $jProc\t" >> ${OPENSHIFT_DATA_DIR}/log/deploy.log
    done
}

printJvmCount
