#!/bin/bash

cleanRuntime() {
    echo -en "cleanRuntime() \n";
    rm $HOME/$OPENSHIFT_GEAR_TYPE/$OPENSHIFT_GEAR_TYPE/standalone/log/server.log
}

createSoftLinksToWebArchives() {
    echo -en "createSoftLinksToWebArchives() \n";
    cd $OPENSHIFT_RUNTIME_DIR/repo/deployments;

    ln -s ~/$OPENSHIFT_GEAR_TYPE/tmp/deployments/${console.server.name}
    touch ${console.server.name}.dodeploy
    ln -s ~/$OPENSHIFT_GEAR_TYPE/tmp/deployments/${console.name}
    touch ${console.name}.dodeploy
}

cleanRuntime
createSoftLinksToWebArchives
