#!/bin/bash

logTimestamp() {
    mkdir  -p ${OPENSHIFT_DATA_DIR}/log
    echo `date` > ${OPENSHIFT_DATA_DIR}/log/post_start_postgresql.log
}

# Test remote host:port availability (TCP-only as UDP does not reply)
function checkRemotePort() {
    (echo >/dev/tcp/$OPENSHIFT_POSTGRESQL_DB_HOST/$OPENSHIFT_POSTGRESQL_DB_PORT) &>/dev/null
    if [ $? -eq 0 ]; then
        echo -en "\ndeploy.checkRemotePort() : $OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT is open.\n\n"
    else
        echo -en "\ndeploy.checkRemotePort() : $OPENSHIFT_POSTGRESQL_DB_HOST:$OPENSHIFT_POSTGRESQL_DB_PORT is closed. ... will now exit\n\n"
        exit 1
    fi
}

# TO_DO:  this should be configurable as per 'hibernate.hbm2ddl.auto' property
POSTGRESQL_DBModifications() {
    echo -en "deploy.POSTGRESQL_DBModifications() ... start\n"
    #psql -c "drop database if exists jbpm;"
    #psql -c "drop user if exists jbpm;"
    #psql -c "create user jbpm with password 'jbpm';"
    #psql -c "create database jbpm with owner=jbpm;"

    #psql -c "drop database if exists jbpm_bam;"
    #psql -c "drop user if exists jbpm_bam;"
    #psql -c "create user jbpm_bam with password 'jbpm_bam';"
    #psql -c "create database jbpm_bam with owner=jbpm_bam;"

    #psql -c "drop database if exists guvnor;"
    #psql -c "drop user if exists guvnor;"
    #psql -c "create user guvnor with password 'guvnor';"
    #psql -c "create database guvnor with owner=guvnor;"

    echo -en "deploy.POSTGRESQL_DBModifications()  ... completed.\n\n"
}

logTimestamp
checkRemotePort
POSTGRESQL_DBModifications
