#!/bin/bash

socketIsOpen=2

# Test remote host:port availability (TCP-only as UDP does not reply)
function checkRemotePort() {
    (echo >/dev/tcp/$OPENSHIFT_${openshift.jdbc.module.name}_DB_HOST/$OPENSHIFT_${openshift.jdbc.module.name}_DB_PORT) &>/dev/null
    if [ $? -eq 0 ]; then
        echo -en "\npost_deploy.checkRemotePort() : $OPENSHIFT_${openshift.jdbc.module.name}_DB_HOST:$OPENSHIFT_${openshift.jdbc.module.name}_DB_PORT is open.\n\n"
    else
        echo -en "\npost_deploy.checkRemotePort() : $OPENSHIFT_${openshift.jdbc.module.name}_DB_HOST:$OPENSHIFT_${openshift.jdbc.module.name}_DB_PORT is closed. ... will now exit\n\n"
        exit 1
    fi
}

# TO_DO:  this should be configurable as per 'hibernate.hbm2ddl.auto' property
${openshift.jdbc.module.name}_DBModifications() {
    echo -en "post_deploy.${openshift.jdbc.module.name}_DBModifications() ... start\n"
    psql -c "drop database if exists jbpm;"
    psql -c "drop user if exists jbpm;"
    psql -c "create user jbpm with password 'jbpm';"
    psql -c "create database jbpm with owner=jbpm;"

    psql -c "drop database if exists jbpm_bam;"
    psql -c "drop user if exists jbpm_bam;"
    psql -c "create user jbpm_bam with password 'jbpm_bam';"
    psql -c "create database jbpm_bam with owner=jbpm_bam;"

    psql -c "drop database if exists guvnor;"
    psql -c "drop user if exists guvnor;"
    psql -c "create user guvnor with password 'guvnor';"
    psql -c "create database guvnor with owner=guvnor;"

    echo -en "post_deploy.${openshift.jdbc.module.name}_DBModifications()  ... completed.\n\n"
}

printJvmCount() {
    mkdir  -p ~/${openshift.jboss.cartridge.type}/tmp/log
    echo `date` > ~/${openshift.jboss.cartridge.type}/tmp/log/post_deploy.log
    for jProc in `ps -C java -o pid=`;
    do
        echo "java process id = $jProc\t" >> ~/${openshift.jboss.cartridge.type}/tmp/log/post_deploy.log
    done
}
printJvmCount


sleep 2
checkRemotePort
${openshift.jdbc.module.name}_DBModifications
