#!/bin/bash

echo "** inside pre_start_jbosseap "

modifyJvmSettings() {
    # now increasing PermGen and lowering heap
    echo -en "pre_start_jbosseap:  about to modify jvm settings\n"
    export JAVA_OPTS="-client -Xmx664m -XX:MaxPermSize=256m -XX:+AggressiveOpts -Dorg.jboss.resolver.warning=true -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djboss.node.name=${OPENSHIFT_GEAR_DNS} -Djgroups.bind_addr=${OPENSHIFT_JBOSSEAP_IP} -Dorg.apache.coyote.http11.Http11Protocol.COMPRESSION=on"
    export OPENSHIFT_JBOSSEAP_MODULE_PATH=${openshift.pfpcore.config.dir}/pfpModules:${openshift.pfpcore.config.dir}/gpseModules
}

printJvmCount() {
    mkdir -p ${OPENSHIFT_DATA_DIR}/log
    echo `date` > ${OPENSHIFT_DATA_DIR}/log/pre_start_jbosseap.log
    for jProc in `ps -C java -o pid=`;
    do
        echo "java process id = $jProc\t" >> ${OPENSHIFT_DATA_DIR}/log/pre_start_jbosseap.log
    done 
}


killExistingJavaProcesses() {
    for jProc in `ps -C java -o pid=`;
    do
        echo -en "about to kill java process id = $jProc\n"
        kill -9 $jProc
    done

    rm -f ${openshift.jboss.cartridge.type}/standalone/log/boot.log
}

cleanRuntime() {
    if [ -e $HOME/${openshift.jboss.cartridge.type}/standalone/log/server.log ]
    then
        echo -en "cleanRuntime() \n";
        rm $HOME/${openshift.jboss.cartridge.type}/standalone/log/server.log
    fi

}
printJvmCount
killExistingJavaProcesses
cleanRuntime
modifyJvmSettings
