#!/bin/bash

printJvmCount() {
    mkdir -p ${OPENSHIFT_DATA_DIR}/log
    echo `date` > ${OPENSHIFT_DATA_DIR}/log/pre_build.log
    for jProc in `ps -C java -o pid=`;
    do
        echo "java process id = $jProc\t" >> ${OPENSHIFT_DATA_DIR}/log/pre_build.log
    done
}
printJvmCount

